### ISSUE TITLE
updatedb fail

### ISSUE THREAD

**Issue by jaspercn1982** [IBM/wc-devops-utilities#16] opened 2018-07-24 08:34 UTC
This is the error found in log. It seems it didn't get vault correctly.

running Vault config mode with vaultConfigure.sh
parse error: Invalid numeric literal at line 1, column 3
set DOMAIN_NAME as default value.
use domain name: default.svc.cluster.local.
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
parse error: Invalid numeric literal at line 1, column 3
DBHOST has no value.

**Comment by kongyi-ibm** [comment] 2018-07-25 04:42
This issue has been fixed in commit [refine folder name by change kubernetes to utilties](https://github.com/IBM/wc-devops-utilities/commit/057cb31a2941a5aa4fd6eadcf74bbfbe3933a570)

The root cause is that we changed the vault url by remove the version inform ( e.g v1/ ), because vault python modul changed the default behavior, but new Daily Job will use the same vault url, but it will curl vault directly.  

The error caused by the vault url be used in curl command is incorrect.  I have change the jenkins job to add the "v1/" for vault url value.

**Closed** 2018-07-25 04:43 UTC
Labels: bug
